### ISSUE TITLE
Add extra checks to your library

### ISSUE THREAD

**Issue by dmitryrPlanner5D** [dimitree54/ai_code_reviewer#30]
- soft single-responsibility: suggest split too long methods or methods with too deep nest of for cycles
- decouple debug logic and production code
- avoid matching by string, prefer variables or enums
- decouple creation logic from logic (dependency injection)
- check for proper patterns usage. For example, build method should actually be build method, not factory

**Comment by dimitree54** [comment]
Test should assert something

**Comment by dimitree54** [comment]
Avoid prints

**Comment by dimitree54** [comment]
The should be no debug code left. For example, local paths

**Comment by dimitree54** [comment]
Prefer Path lib over str + os.path
